server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1000000
  max_block_duration: 5m
  lifecycler:
    ring:
      kvstore:
        store: memberlist

memberlist:
  join_members:
    - tempo:7946

storage:
  trace:
    backend: local

    wal:
      path: /var/tempo/wal

    local:
      path: /var/tempo/blocks

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 10000000
    block_retention: 24h
    compacted_block_retention: 1h

metrics_generator:
  ring:
    kvstore:
      store: memberlist

  # optional แต่ดีถ้ามี ให้ label metrics ว่ามาจาก tempo
  registry:
    external_labels:
      source: tempo

  storage:
    path: /var/tempo/metrics-generator

  processor:
    service_graphs: {}
    span_metrics: {}
    # 👇 ต้องใช้ชื่อ local_blocks (underscore) ไม่ใช่ local-blocks
    local_blocks: {}

overrides:
  # ตรงนี้เป็นแค่ list string เลยใช้ชื่อแบบที่ Grafana/เอกสารพูดถึงได้
  metrics_generator_processors:
    - service-graphs
    - span-metrics
    - local-blocks